### ISSUE TITLE
/Users/GinaYang/Desktop/lz_works/youbao-internet-clinic-app-rn/node_modules/react-native-clear-cache/android/src/main/java/com/reactlibrary/ClearCacheModule.java:13: 错误: 程序包android.support.annotation不存在 import android.support.annotation.Nullable;

### ISSUE THREAD

**Issue by aijason** [sowlutions/react-native-clear-cache#1]
/Users/GinaYang/Desktop/lz_works/youbao-internet-clinic-app-rn/node_modules/react-native-clear-cache/android/src/main/java/com/reactlibrary/ClearCacheModule.java:13: 错误: 程序包android.support.annotation不存在
import android.support.annotation.Nullable;

**Comment by Gazfay** [comment]
@aijason how did you fix this issue?
